### ISSUE TITLE
Pics or it didn't happen

### ISSUE THREAD

**Issue by joakim** [borisyankov/react-sparklines#1]
Most people are too lazy to clone a repo or install a module just to see what it looks like, me included :wink:

Looking forward to seeing what it looks like!

**Comment by borisyankov** [comment]
It certainly did happen! :)
Working on a nice gh-pages site in the next 1-2 days.

**Comment by borisyankov** [comment]
Fixed ;)

**Comment by joakim** [comment]
Lived up to my expectations too, great stuff :+1:
