### ISSUE TITLE
Importing from the package causes application to crash

### ISSUE THREAD

**Issue by ahmedmoazasif** [borisyankov/react-sparklines#106]
Version used: 1.6.0

The issue is caused when developing an application built with create-react-app.

The import statement throws an error when using yarn start to run the react application.

[React App.zip](https://github.com/borisyankov/react-sparklines/files/1622528/React.App.zip)

**Comment by lch2001** [comment]
I get the following error in the JS console trying to import the package:

> TypeError: Super expression must either be null or a function, not undefined

**Comment by aayush1408** [comment]
Importing the package causes app to breakdown,and its not only in the case of 'create-react-app' but also with the webpack.
Version:1.7.0

**Comment by volodfast** [comment]
In my case it was because of the React. The react-sparklines uses PureComponent which was added in v15.3 so you should update React in your app in order to use this component.

**Comment by ahmedmoazasif** [comment]
On the latest version of react, use the latest version of react-sparklines and restart the development server using 'npm start'
Solved the issue for me. Issue arose due to using version 1.6.0 of react-sparklines with the latest version of react and the dev server caching the loaded modules

**Comment by BumbuKhan** [comment]
Just try to install one of the prev version.

For example `npm install --save react-sparklines@1.0.3` solved the issue of mine.

P.S
You can the list of prev. versions by running `npm view react-sparklines`
the version of react was `0.14.3`

**Comment by majidzeno** [comment]
@BumbuKhan I tried @1.0.3 but never solve the issue, the problem seems because of the old version is not matched with the latest version of React ( Proptypes ) is not used anymore - As I think - but latest version works fine.
