### ISSUE TITLE
Package not working with react 16.3.14

### ISSUE THREAD

**Issue by jul1ans** [borisyankov/react-sparklines#117]
This package is unfortunately not working with react 16.3.14.
If I use react-sparklines@1.6.0 the following error appears:

> _react2.default.PropTypes.string is undefined.

If I use the version 1.7.0 the graph is not rendered:

`<svg viewBox="0 0 120 80" preserveAspectRatio="none"></svg>`

I use a basic setup from the documentation:

`<Sparklines height={80} width={120} data={[2,3,4,5,6]}>
   <SparklinesLine color="red" />
</Sparklines>`

Thank you for helping

**Comment by matttk** [comment]
I'm using 16.4.1 and it's working just fine. My only problem was that I had to set the width of the div manually or it didn't show. Might sound stupid but double-check that!

**Comment by jul1ans** [comment]
@matttk thank you for your help. 
Which react-sparklines version do you use?

**Comment by matttk** [comment]
Whatever is the latest. I just did npm install today.

**Comment by jul1ans** [comment]
That works! Thanks a lot :)

With the following configuration the sparkline will be rendered:

`<div style={{width: '120px'}}>
  <Sparklines height={80} width={120} data={[2,3,4,3,4]}>
    <SparklinesLine color="red" />
  </Sparklines>
</div>`
