### ISSUE TITLE
shouldComponentUpdate throws error

### ISSUE THREAD

**Issue by okonet** [borisyankov/react-sparklines#12]
It seems these lines https://github.com/borisyankov/react-sparklines/blob/master/src/Sparklines.js#L32-L34 should compare `nextProps` with `this.props`, but now it is trying to compare with `nextState` which is `null` and this throws an error `TypeError: Cannot read property 'width' of null`

**Comment by okonet** [comment]
Could you please publish a fix to NPM?

**Comment by borisyankov** [comment]
Pushed as 1.1.2 ;)

**Comment by okonet** [comment]
:rocket:
