### ISSUE TITLE
Current tests are failing

### ISSUE THREAD

**Issue by okonet** [borisyankov/react-sparklines#17]

**Comment by borisyankov** [comment]
Fixed. Though a single test is hardly anything to brag about.
Jest used to fail on my machine before, that is the reason for the missing test suit.
Should probably work on that.

**Comment by okonet** [comment]
I'm adding some tests but struggling with Jest. Do you mind switching to mocha?

**Comment by borisyankov** [comment]
Not at all, there is no 'investment' in Jest yet ;)
Jest is also slow.
Go ahead with Mocha.

**Comment by okonet** [comment]
I've just pushed #19
