### ISSUE TITLE
Required prop `points` was not specified in `SparklinesBars`

### ISSUE THREAD

**Issue by j42** [borisyankov/react-sparklines#22]
I have this error when I use SparklineBars as per your exampe (in 1.3 and 1.2.2).

Adding the 'points' prop as an array such as `[5,10,5,20,10,50]` which SHOULD work for React.PropTypes.arrayOf(React.PropTypes.number).isRequired.

For some reason this doesn't happen, and it gives me an error:

Warning: Failed propType: Invalid prop `points[0]` of type `object` supplied to `SparklinesBars`, expected `number`. Check the render method of `Sparklines`.

Thoughts?

**Comment by sudhakar** [comment]
Facing same problem. ```SparklinesBars``` parent ```Sparklines``` redefines points as array of objects(even if the source is array of numbers). Havent dived deep into the codebase, but looks like it should be defined as ```React.PropTypes.arrayOf(React.PropTypes.object).isRequired```

**Comment by ericp96** [comment]
Has anyone found a workaround for this?

**Comment by viaScully** [comment]
same issue here... 

in Sparklines.js it appears that 'points' is somewhat of an internal constant created from the data submitted and not meant to be specified in the JSX tag.  

I'm still new to React myself.  I'm not sure why the demo.js code seems to load fine without reporting those errors (or specifying a 'points' attribute), but I can't seem to avoid it.

I have a similar issue with the 'height' attribute of SparklineBars, which appears that it should be set internally based on the height of the Sparklines element.

**Comment by mattparrilla** [comment]
:+1: to this, as well as the `height` attribute.

**Comment by nickweinberg** [comment]
Same. Any updates?
