### ISSUE TITLE
data is not dereferenced

### ISSUE THREAD

**Issue by DimitarChristoff** [borisyankov/react-sparklines#27]
It's accepting the data passed in and checking if it should render:

```
    shouldComponentUpdate(nextProps) {
        return nextProps.width != this.props.width ||
            nextProps.height != this.props.height ||
            nextProps.margin != this.props.margin ||
            nextProps.data.length != this.props.data.length ||
            nextProps.data.some((d, i) => d !== this.props.data[i]);
    }
```

so `data={this.state.data}` -> passed by reference to your `props.data`.

higher up if a change happens in data array (an item), it is comparing it against itself. `nextProps.data.some((d, i) => d !== this.props.data[i]);` 

a quick workaround is to do `data={this.state.data.slice()} ` upstream but it probably should be handled at your end or a different diff mechanism should be provided, eg `forceUpdate={true}`.

in my use case, the array is already limited to 30 points so length won't ever change, it's shifting first member and pushing to end. I can force an update by toggling margin to a diff value on every tick locally

**Comment by borisyankov** [comment]
Do you still have the problem (with the latest version)?
