### ISSUE TITLE
Last bar in SparklinesBars is getting clipped off

### ISSUE THREAD

**Issue by joshthecoder** [borisyankov/react-sparklines#28]
You can kind of see this happening in the demos. Seems the width calculations are off a bit
causing the last bar to extend outside the width of the svg element.

![screen shot 2015-11-20 at 1 05 10 am](https://cloud.githubusercontent.com/assets/25644/11295790/ccb0c088-8f22-11e5-8703-4cac486a0ee0.png)

**Comment by mquirion** [comment]
I'm experiencing the same issue. Is this being worked on?  I could take a look at fixing it and sending a PR if not.

**Comment by borisyankov** [comment]
I was intending to fix it, but didn't had the time.
It is a bit tricky, because bars and lines use the same calculated values, and bars have widths ;)
A workaround is to add margins to the chart, but of course not ideal.

If you can fix and submit a PR, that will be great ;)

**Comment by Sigura** [comment]
PR #31

And thank you for you nice work! ,)
