### ISSUE TITLE
Remove direct React dependency?

### ISSUE THREAD

**Issue by ericelliott** [borisyankov/react-sparklines#3]
Depending directly on React from reusable components can cause problems stemming from competing React instances, and version conflicts. See [Two React Tips](https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375).

One way around this is to export a function, that takes an options object & allow users to inject the React dependency in the options object. See [Baby's First Reaction](https://medium.com/javascript-scene/baby-s-first-reaction-2103348eccdd) for an example.

**Comment by borisyankov** [comment]
@ericelliott thanks a lot for the notes.
I read the articles, very helpful.
Do you think targeting '*' React version is enough to resolve the issue?

**Comment by ericelliott** [comment]
> Do you think targeting '*' React version is enough to resolve the issue?

No. However, this may get easier with React 0.14+, which splits some of the React dependencies you may need out of the React module.

You may also be interested in [react-stampit](https://github.com/stampit-org/react-stampit), which also demonstrates using dependency injection to let users pass in the React dependency and avoid React instance conflicts.

**Comment by mattgi** [comment]
I cannot add this package when running the latest version of react.

```
npm ERR! peerinvalid The package react@0.14.0-beta3 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-sparklines@1.0.3 wants react@*
```

Any chance we can remove the peerDependency?

**Comment by khakulov** [comment]
+1
