### ISSUE TITLE
With constant value, the line disappears.

### ISSUE THREAD

**Issue by chundongwang** [borisyankov/react-sparklines#39]
With data array of constant value in it, the line disappeared.
```
           <Sparklines data={[1,1,1,1,1,1]}>
                <SparklinesLine />
            </Sparklines>
```
The reason is the way DataProcessor.dataToPoints() handles max===min situation incorrectly.

I prepared a fix to put such line in the middle of plot area which looks good to me.

**Comment by benvinegar** [comment]
This is a pretty serious problem with react-sparklines – if you ever get data that produces a flat line, the sparkline basically vanishes.

**Comment by borisyankov** [comment]
Fixed in latest published version.
