### ISSUE TITLE
Please publish built files

### ISSUE THREAD

**Issue by timoxley** [borisyankov/react-sparklines#4]
Currently the package published on npm depends on ES6 source code, which is a PITA for anyone consuming this package needs to figure out how to special case `react-sparklines` in their build system, if they're using one. Can't even use an existing ES6 setup if you're not using stage 0 features.

Please set the package.json `main` to point only at built source in the published package – this enables anyone to use `react-sparklines` whether they're using a build tool, ES6 or whatever. This is [exactly the usecase that `npm prepublish` scripts are designed for](https://docs.npmjs.com/misc/scripts#common-uses).

**Comment by konsumer** [comment]
+1
