### ISSUE TITLE
Provide build for browser

### ISSUE THREAD

**Issue by messinm** [borisyankov/react-sparklines#43]
Would like to be able to use a pre-built lib suitable for browser <script> tag. Can this be provided in the repo? or make available elsewhere.

**Comment by borisyankov** [comment]
It can already be used if you get the index.js file in the build folder.
Or even easier, you can reference to the latest build on npm via the cool service npmcdn. 
The file to link to is:
https://npmcdn.com/react-sparklines@1.5.0/build/index.js

**Comment by messinm** [comment]
Thanks, I'll try that.

**Comment by messinm** [comment]
Found the problem -
Need to do it like this -
ReactDOM.render(
  React.createElement(ReactSparklines.Sparklines, {
      data: [0, 10, 12, 32, 12, 1]
    },
    React.createElement(ReactSparklines.SparklinesCurve, {})),
  document.getElementById('s0')
);
