### ISSUE TITLE
Realtime Ping results as output

### ISSUE THREAD

**Issue by pavs** [borisyankov/react-sparklines#44]
Will it be possible to show near realtime ping latency/performance using react sparklines?

**Comment by borisyankov** [comment]
Yeah. The performance of the component is really good.
I've tested it with several hundred instances (that is the amount when the perf really gets a hit).
So I'd say you will easily hit 60 updates per second.

**Comment by pavs** [comment]
ok thanks. :) Now I will have to figure out how to implement it.
