### ISSUE TITLE
Support for react v15.0

### ISSUE THREAD

**Issue by gfarrell** [borisyankov/react-sparklines#50]
React 15 has nice performance enhancements and better svg support. I imagine `sparklines` *probably* works with it, but it would be nice to bump support up if it is fully compatible.

**Comment by borisyankov** [comment]
It does work with React 15, I have tested it for a while.
There is no change needed to the project itself.
The package.json dependencies indicate the minimum supported version.

**Comment by gfarrell** [comment]
I get warnings that 15.x doesn't satisfy the peer deps (^ rather than >)






On Thu, Apr 14, 2016 at 5:40 AM -0700, "Boris Yankov" <notifications@github.com> wrote:












It does work with React 15, I have tested it for a while.

There is no change needed to the project itself.

The package.json dependencies indicate the minimum supported version.

**Comment by borisyankov** [comment]
Try the latest build, just published.

**Comment by KevinGrandon** [comment]
It should work in master, but not the version published to npm. Could you publish a new version to npm? Thanks!

**Comment by zenonn37** [comment]
1+ Thanks

**Comment by borisyankov** [comment]
I did publish a version with dependencies of version '*'.
Lets see if that works.
