### ISSUE TITLE
Component names API

### ISSUE THREAD

**Issue by nkt** [borisyankov/react-sparklines#6]
I suggest you to rename components until this component became very popular:
 - `SparklinesLine` to `Line`
 - `SparklinesBars` to `Bars`
 - `SparklinesSpots` to `Spots`
 - `SparklinesReferenceLine` to `ReferenceLine`
 - `SparklinesNormalBand` to `NormalBand`

There is no need in `Sparklines` prefix, because everyone use `common.js` or ES6 modules, right?

**Comment by borisyankov** [comment]
I agree, there is a bit of redundancy in the names.
On the other hand Line, Bars and Spots seem way too common.
I'll consider the options early, thanks for mentioning that.

**Comment by sahat** [comment]
Agreed, it would look cleaner like this with ES6:

```js
import {Line, Bars, ReferenceLine} from 'react-sparklines';
```

But on the other hand, I don't see any relationship between these components. `Line` could be some custom component that someone else wrote on the team:

```js
<Sparklines data={sampleData}>
    <Line style={{ fill: "none" }}/>
</Sparklines>
```

**Comment by nkt** [comment]
@borisyankov if you worry about debugging, you can set these names in `displayName`.
Also using ES6 you can redefine export name:
```js
import {Line as SparklinesLine} from 'react-sparklines';
```
