### ISSUE TITLE
npm issue

### ISSUE THREAD

**Issue by ndjoe** [borisyankov/react-sparklines#7]
well i dont know what is wrong, any clue guys?

> Line 1: Unexpected reserved word
>You may need an appropriate loader to handle this file type.
>| import React from 'react';
>| import SparklinesLine from './SparklinesLine';
>| import SparklinesBars from './SparklinesBars';
> @ ./~/react-sparklines/index.js 1:17-47

**Comment by borisyankov** [comment]
Is it possible that you have not included 'babel' in the webpack loader list?
It is needed to transpile ES6 code (which import is part of).
Have a look at the webpack.config.js file in this project for an example.

**Comment by johnnypez** [comment]
I think you should be using a prepublish script to transpile your es6 modules before publishing to npm rather than impose a build step on anyone that wants to use your package. See here for example http://mammal.io/articles/using-es6-today

**Comment by borisyankov** [comment]
Good point.
Thanks for pointing it out.

**Comment by j42** [comment]
Just wanted to mention this issue tripped me up too...

```
[17:05:48] Starting 'browserify'...
[17:05:48] Finished 'browserify' after 23 ms
[17:05:48] Starting 'fonts'...
[17:05:48] Finished 'fonts' after 6.76 ms
[17:05:48] Starting 'scss'...
[17:05:48] Finished 'scss' after 11 ms
[17:05:48] Starting 'watch'...
[17:05:48] Finished 'watch' after 27 ms
[17:05:48] Starting 'default'...
[17:05:48] Finished 'default' after 7.33 μs

/home/vagrant/Code/my-source.co/node_modules/react-sparklines/src/Sparklines.js:1
import React from 'react';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'```

**Comment by standino** [comment]
The package in https://www.npmjs.com/package/react-sparklines is old. Could you publish a new one? Thanks.

**Comment by borisyankov** [comment]
Done.

**Comment by standino** [comment]
Thanks! @borisyankov
