### ISSUE TITLE
Publish/bump npm version

### ISSUE THREAD

**Issue by hampusohlsson** [borisyankov/react-sparklines#88]
Hey @borisyankov, thanks for merging #83

Would be great if you bumped the version and published to npm 😄

**Comment by borisyankov** [comment]
Hey, @hampusohlsson I just did publish a new release. Let me know if it works for you.

Try it out. I'll do some more maintenance changes in the next few days.

**Comment by hampusohlsson** [comment]
Awesome! Thanks
