### ISSUE TITLE
Error while importing the package with Super()

### ISSUE THREAD

**Issue by YahiaElTai** [borisyankov/react-sparklines#94]
quick question please, 
i'm working on a react-redux app and i'm trying to display a chart with Sparklines, but as soon as i import the package, i get an Error that looks like this:
**Uncaught TypeError**:  Super expression must either be null or a function, not undefined.
here's the container that i'm working with at the moment.

**Container**
```
import React , {Component} from 'react';
import {connect} from 'react-redux';
import { Sparklines, SparklinesLine } from 'react-sparklines';

// code

renderWeather(cityData) {
    const name = cityData.city.name;
    const temps = cityData.list.map( current => current.main.temp);
    return (
      <tr key={name}>
        <td>{name}</td>
        <td>
        <Sparklines height={120} width={180} data={temps}>
            <SparklinesLine color="red"/>
        </Sparklines>
        </td>
      </tr>
      );
  }
// code
```

if you need any additional info, please let me know. 
thanks alot

**Comment by yedeyu** [comment]
- install version 1.6.0 instead
```
npm i --save react-sparklines@1.6.0
```

More in https://github.com/borisyankov/react-sparklines/issues/89#issuecomment-322317332

**Comment by YahiaElTai** [comment]
thanks so so much that solved my problem.
